# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/julia/Documents/GitHub/CISC24/CISC24/CISC24.srcs/sources_1/new/Nexys-4-DDR-Master.xdc

# Block Designs: bd/BlockRAM/BlockRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRAM || ORIG_REF_NAME==BlockRAM} -quiet] -quiet

# IP: bd/BlockRAM/ip/BlockRAM_blk_mem_gen_0_0/BlockRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlockRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==BlockRAM_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/BlockRAM/BlockRAM_ooc.xdc
